### ISSUE TITLE
ionic serve

### ISSUE THREAD

**Issue by timsar2** [lionelquellery/Batch-Ionic-3#1]
Error: Uncaught (in promise): ReferenceError: batch is not defined
ReferenceError: batch is not defined
    at BatchService.webpackJsonp.264.BatchService.batchStarter (http://localhost:8100/build/main.js:340:9)
(i forgot to run this on device. this error is from browser maybe cuze of non cordova on it)
but inside of emulator no toke will be parse to server 
this log is from emulator:

`5.358 30396 30483 W PluginManager: THREAD WARNING: exec() call to Batch.BA_setConfig blocked the main thread for 78ms. Plugin should use CordovaInterface.getThreadPool().
08-03 13:45:55.367 30396 30396 W m.ionic.starte: Attempt to remove non-JNI local reference, dumping thread
08-03 13:45:55.406 30396 30396 I chatty  : uid=10087(com.ionic.starter) identical 2 lines
08-03 13:45:55.428 30396 30396 W m.ionic.starte: Attempt to remove non-JNI local reference, dumping thread
08-03 13:45:55.430 30396 30483 I m.ionic.starte: Rejecting re-init on previously-failed class java.lang.Class<com.batch.android.BatchPushInstanceIDService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceIDListenerService;
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at com.batch.android.k.f com.batch.android.i.g.v() (SourceFile:985)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at void com.batch.android.i.g.d() (SourceFile:972)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at void com.batch.android.i.c.d() (SourceFile:51)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at com.batch.android.m.e com.batch.android.Batch$13.a(com.batch.android.m.e) (SourceFile:1898)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at boolean com.batch.android.m.c.a(com.batch.android.m.a) (SourceFile:108)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at void com.batch.android.Batch.a(android.content.Context, boolean, boolean) (SourceFile:1668)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at void com.batch.android.Batch.onStart(android.app.Activity) (SourceFile:1573)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at void com.batch.cordova.interop.Bridge.start(android.app.Activity) (Bridge.java:262)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at com.batch.cordova.interop.SimplePromise com.batch.cordova.interop.Bridge.doAction(java.lang.String, java.util.Map, android.app.Activity) (Bridge.java:93)
08-03 13:45:55.430 30396 30483 I m.ionic.starte:   at com.batch.cordova.interop.SimplePromise com.batch.cordova.interop.Bridge.call(java.lang.String, java.util.Map, com.batch.cordova.interop.Callback, androi`

**Comment by lionelquellery** [comment]
Hi @timsar2 thank for your feedback, are you testing on your browser or real device?  

Keep in mind, you need to use a real device if you want to work with Batch SDK.  

You can follow this documentation. It's very straightforward https://ionicframework.com/docs/v1/guide/testing.html

Let me know if it's not clear

**Comment by timsar2** [comment]
i was test on browser.
use 
`ionic cordova emulate android -a -b -s -c -l`
and it's done.
